TOKENS = {
    'if': '<IF_TK>',
    'else': '<ELSE_TK>',
    'elif': '<ELIF_TK>',
    'for': '<FOR_TK>',
    'while': '<WHILE_TK>',
    'def': '<DEF_TK>',
    'print': '<PRINT_TK>',
    'class': '<CLASS_TK>',

    '=': '<ASSIGN_TK>',
    '.': '<DOT_TK>',
    ':': '<COLON_TK>',
    ';': '<SEMICOLON_TK>',
    ',': '<COMMA_TK>',
    "'": '<SQUOTES_TK>',
    '"': '<DQUOTES_TK>',
    ',': '<COMMA_TK>',
    '(': '<PARANTES_OPEN_TK>',
    ')': '<PARANTES_CLOSE_TK>',
    '{': '<CBRACKET_OPEN_TK>',
    '}': '<CBRACKET_CLOSE_TK>',
    '[': '<BRACKET_OPEN_TK>',
    ']': '<BRACKET_CLOSE_TK>',

    '+': '<PLUS_TK>',
    '*': '<MUL_TK>',
    '-': '<MINUS_TK>',
    '/': '<SLASH_TK>',
    '==': '<EQ_TK>',
    '!=': '<NOT_EQ_TK>',
    '<': '<LESS_TK>',
    '>': '<GREATER_TK>',
    '<=': '<LE_TK>',
    '>=': '<GE_TK>',
}